# Generated by Django 2.0.2 on 2019-01-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20190108_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='titlee',
        ),
    ]
